const CONSTANTS = {
  countries: {
    china: 'Китай',
    russia: 'Россия',
    'great britain': 'Великобритания',
  },
  appVersion: '2.30.1',
  bgTextLen: 16000,
  smTextLen: 800,
  videoTextLen: 1500,
  symbolsToIgnore: [
    ' ',
    '．',
    '。',
    '，',
    '、',
    '：',
    '“',
    '”',
    '？',
    '?',
    '!',
    '！',
    '；',
    ';',
    ',',
    '.',
    '（ ',
    '）',
    '【',
    '】',
    '［',
    '］',
    '(',
    ')',
    '》',
    '《',
    '‧',
    '〈',
    '〉',
    "'",
    '_',
    '-',
    '—',
    '「',
    '」',
    '\n',
  ],
  textCategories: [
    'Учебные, HSK',
    'Детское',
    'Док-ты, бизнес',
    'Новости',
    'Наука и техника',
    'Литература',
    'Познавательное',
    'Вэньянь',
    'Еда и рецепты',
    'Медицина',
    'IT',
    'Юмор',
  ],
  videoCategories: {
    misc: 'разное',
    song: 'песня',
    ads: 'реклама',
    cartoon: 'анимация',
    sciense: 'наука',
    documentary: 'документальное',
    news: 'новости',
  },
  blogCategories: {
    general: 'Общее',
    personal: 'Личный опыт',
    study: 'Обучение',
    culture: 'Культура',
    club_news: 'Новости клуба',
    mini_post: 'Мини-пост',
    literature_poetry: 'Литература и поэзия',
    suggestion_bug: 'Предложения и баги',
    history: 'История',
    it_stuff: 'IT',
    food: 'Еда',
    travel: 'Путешествия',
  },
  commentLength: 900,
  commentEmojis: [
    '🔥',
    '🙏🏻',
    '👍',
    '👎',
    '👌',
    '💩',
    '😀',
    '😞',
    '🤦‍',
    '❤️',
    '🚀',
    '💪',
    '🤣',
    '🤷‍',
  ],
  hskInfo: {
    bandSize: {
      '1': 500,
      '2': 772,
      '3': 973,
      '4': 1000,
      '5': 1071,
      '6': 1140,
      '7-8-9': 5636,
    },
    oldLevelSize: {
      '1': 150,
      '2': 150,
      '3': 300,
      '4': 600,
      '5': 1300,
      '6': 2500,
    },
  },
  maxWordsPerPage: 200,
  maxThemePicRequests: 5,
  users: {
    vocabSize: 300,
  },
  CONTENT: {
    video: 'video',
    text: 'text',
    post: 'post',
  },
};

export type HskLvlSizeMap = {
  [key: string]: number;
};

export default CONSTANTS;
