version: "3.8"

services:
  mongo_chin_dev:
    image: mongo
    container_name: mongo_chin_dev
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      new_bylh_bylh_net:

  chin_plus_be:
    container_name: chin_plus_be
    image: chin_plus_be:${VERSION}
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - 10000:10000
    environment:
      BE_VERSION: ${VERSION}
    env_file:
      - ./server/config/.env.prod
    networks:
      new_bylh_bylh_net:

  chin_plus_fe:
    container_name: chin_plus_fe
    image: chin_plus_fe:${VERSION}
    restart: unless-stopped
    environment:
      - VERSION=${VERSION}
    build:
      context: ./qwik
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
        BE_PORT: 10000
    ports:
      - 4000:3000
    networks:
      new_bylh_bylh_net:

volumes:
  mongodata:

networks:
  new_bylh_bylh_net:
    external: true
