version: "3.8"

services:
  mongo_chin_dev:
    image: mongo
    container_name: mongo_chin_dev
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      bylh_net:

  chin_plus_be:
    container_name: chin_plus_be
    image: chin_plus_be:${BE_VERSION}
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - 10000:10000
    environment:
      BE_VERSION: ${BE_VERSION}
      MONGO_DB: ${MONGO_DB}
      AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      AUTH_GOOGLE_SECRET: ${AUTH_GOOGLE_SECRET}
    networks:
      bylh_net:

  chin_plus_fe:
    container_name: chin_plus_fe
    image: chin_plus_fe:${VERSION}
    restart: unless-stopped
    environment:
      - VERSION=${VERSION}
    build:
      context: ./qwik
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
        BE_PORT: 10000
    ports:
      - 4000:3000
    networks:
      bylh_net:

volumes:
  mongodata:

networks:
  bylh_net:
