version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo_chin_dev
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      bylh_net:

  chin_plus_be:
    container_name: chin_plus_be
    restart: unless-stopped
    image: bylh_chin_plus_be:${VERSION}
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 10000:10000
    networks:
      bylh_net:

  chin_plus_fe:
    container_name: chin_plus_fe
    environment:
      - VERSION=${VERSION}
    restart: unless-stopped
    build:
      context: ./qwik
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
        BE_PORT: 10000
    ports:
      - 4000:3000
    networks:
      bylh_net:

volumes:
  mongodata:

networks:
  bylh_net:
