version: "3.1"
services:
  mongo:
    image: mongo
    container_name: mongo_chin_dev
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      bylh_net:

  chin_plus_be:
    container_name: chin_plus_be
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      bylh_net:

  chin_plus_fe:
    container_name: chin_plus_fe
    restart: unless-stopped
    build:
      context: ./qwik
      dockerfile: Dockerfile.dev
    ports:
      - 4000:3000
    networks:
      bylh_net:

volumes:
  mongodata:

networks:
  bylh_net:
