version: "3.8"

services:
  mongo_chin_dev:
    image: mongo
    container_name: mongo_chin_dev
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      bylh_net:

  chin_plus_be:
    container_name: chin_plus_be
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - 10000:10000
    networks:
      bylh_net:

  chin_plus_fe:
    container_name: chin_plus_fe
    image: std016039/chin_plus_fe:${VERSION}
    restart: unless-stopped
    ports:
      - 4000:3000
    networks:
      bylh_net:

volumes:
  mongodata:

networks:
  bylh_net:
