import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";
// import "../styles/Home.module.css";
// import "../styles/light-theme.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>here</div>
      <a href='/pinyin'>pinyin</a>
    </div>
  );
};

export default Home;
