FROM node:20-bookworm as builder
WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci --only=production
RUN npm rebuild

FROM node:20-bookworm
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY . .
CMD npm run start
EXPOSE 10000