FROM node:24-bookworm as builder
WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    pkg-config \
    g++ \
    make \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm ci --only=production --build-from-source

FROM node:24-bookworm-slim
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY . .

CMD npm run start
EXPOSE 10000